export const students=[
    {
        "rollno":34,
        "studentName":"rajeshe",
        "branch":"it",
        "gender":"male"
    },
    {
        "rollno":3,
        "studentName":"rajeshe",
        "branch":"it",
        "gender":"male"
    },
    {
        "rollno":34223,
        "studentName":"rajeshe",
        "branch":"it",
        "gender":"male"
    },
    {
        "rollno":3211,
        "studentName":"rajeshe",
        "branch":"it",
        "gender":"male" 
    },
    {
        "rollno":321,
        "studentName":"rajeshe",
        "branch":"it",
        "gender":"male"
    }
]